service: parameter-store-replicator

provider:
  name: aws
  runtime: nodejs12.x
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ssm:GetParameters"
        - "ssm:GetParameter"
        - "ssm:PutParameter"
        - "ssm:DeleteParameter"
        - "ssm:DeleteParameters"
      Resource: "*"
  environment:
    AWS_TARGET_REGION: ${param:target-region}

functions:
  replicate:
    handler: handler.replicate
    events:
    # for sample events see
    # https://docs.aws.amazon.com/AmazonCloudWatch/latest/events/EventTypes.html#ssm_event_types
      - cloudwatchEvent:
          event:
            source:
              - "aws.ssm"
            detail-type:
              - "Parameter Store Change"
            # ignores params that start with github-actions
            detail:
              name:
                - { "anything-but": { "prefix": "github-actions" } }

plugins:
  - serverless-plugin-diff
